// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShip_DB.Data.Models;

public partial class KoiFish
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string UrlImg { get; set; }

    public bool Status { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ShippingOrderDetail> ShippingOrderDetails { get; set; } = new List<ShippingOrderDetail>();

    public virtual User User { get; set; }
}