// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShip_DB.Data.Models;

public partial class ShipMent
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int ShippingOrdersId { get; set; }

    public string Vehicle { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string HealthCheck { get; set; }

    public string Description { get; set; }

    public bool Status { get; set; }

    public virtual ShippingOrder ShippingOrders { get; set; }

    public virtual User User { get; set; }
}